### ISSUE TITLE
How to fix crash?

### ISSUE THREAD

**Issue by TreeV2** [KyeOnDiscord/csgo-glow-demo-internal#1]
When loading into map my game crash. How can i fix it?
![image](https://user-images.githubusercontent.com/69603592/208252156-4a3f01c6-103c-4e5f-b505-3ef612456111.png)

**Comment by TreeV2** [comment]
its looks like the offsets won t initialize, but still idk how to fix it

**Comment by KyeOnDiscord** [comment]
Dump your own offsets, inject while you are in the game
